#!/usr/bin/env bash

SERVER="bin/server_guard.sh"
LOGFILE="log/populate.log"
TAIL="Follow the log by hitting 'Ctl+Shift+N' and running 'tail -f $LOGFILE'"

clear

echo "Initializing..."
sleep 3

echo "*** Initialized on $(date +%m-%d-%Y) at $(date +%T) ***" >> $LOGFILE

echo

echo "✔"
sleep 2

clear

echo "Alright $USER, please exit the rails server if opened, as well as any test units as they will be utilized during this setup."
sleep 8

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "Resetting..."
bundle exec rake db:reset
echo "✔ Database reset at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Reset"
echo "Populating..."
bundle exec rake db:populate
echo "✔ Database populated at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Reset"
echo "✔ Populate"
echo "Migrating..."
bundle exec rake db:migrate
echo "✔ Database migrated at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Reset"
echo "✔ Populate"
echo "✔ Migrate"
echo "Preparing..."
bundle exec rake db:test:prepare
echo "✔ Database prepared at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Reset"
echo "✔ Populate"
echo "✔ Migrate"
echo "✔ Prepare"
echo "Servers..."
echo "✔ Guard/Spork and Rails Server initialized at $(date +%T)" >> $LOGFILE
bash $SERVER
echo "✔ All servers up and running at $(date +%T)" >> $LOGFILE
sleep 5

clear

echo "✔ Initialize"
echo "✔ Reset"
echo "✔ Populate"
echo "✔ Migrate"
echo "✔ Prepare"
echo "✔ Servers"
echo "*** All tasks completed on $(date +%m-%d-%Y) at $(date +%T) ***" >> $LOGFILE
echo "" >> $LOGFILE

echo

echo "✔ Completed on $(date +%m-%d-%Y) at $(date +%T)"
sleep 5

exit
