#!/usr/bin/env sh

LOGFILE="log/populate.log"
TAIL="Follow the log by hitting 'Ctl+Shift+N' and running 'tail -f $LOGFILE'"

clear

echo "During this setup I am going to create, migrate, populate, and prepare your database for development and testing."
sleep 4

echo

echo "Make sure your database.yml file is setup correctly."
sleep 3

echo

echo "This process will take ~4 minutes."
sleep 4

echo

echo "Initializing..."
sleep 3

echo "*** Initialized on $(date +%m-%d-%Y) at $(date +%T) ***" >> $LOGFILE

echo

echo "✔"
sleep 3

clear

echo "Alright $USER, in the next couple of seconds please close the rails server if opened, as well as any test units as they will be utilized during this setup."
sleep 10

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "Creating..."
rake db:create:all
echo "✔ Database created at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Create"
echo "Migrating..."
rake db:migrate
echo "✔ Database migrated at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Create"
echo "✔ Migrate"
echo "Populating..."
rake db:populate
echo "✔ Database populated at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Create"
echo "✔ Migrate"
echo "✔ Populate"
echo "Preparing..."
rake db:test:prepare
echo "✔ Database prepared at $(date +%T)" >> $LOGFILE

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Create"
echo "✔ Migrate"
echo "✔ Populate"
echo "✔ Prepare"
echo "Servers..."
echo

echo "Alright $USER, in the next few seconds a new terminal window will open."
sleep 5

echo

echo "This window will have three tabs:"
sleep 4

echo

echo "The first is the new workspace once setup is complete..."
sleep 4

echo "...the second is for guard/spork to run their tests..."
sleep 4

echo "...and the third is the rails server."
sleep 3

echo

echo "Allow ~30 seconds for the rails server to initialize."
sleep 4

echo

echo "Once the server has started, a browser window will open and you will be taken to the app."
sleep 6

clear

echo $TAIL
echo
echo "✔ Initialize"
echo "✔ Create"
echo "✔ Migrate"
echo "✔ Populate"
echo "✔ Prepare"
echo "Servers..."
sleep 2
echo "✔ Guard/Spork and Rails Server initialized at $(date +%T)" >> $LOGFILE
. server_guard.sh
echo "✔ All servers up and running at $(date +%T)" >> $LOGFILE
sleep 12

clear

echo "✔ Initialize"
echo "✔ Create"
echo "✔ Migrate"
echo "✔ Populate"
echo "✔ Prepare"
echo "✔ Servers"
echo "*** All tasks completed on $(date +%m-%d-%Y) at $(date +%T) ***" >> $LOGFILE
echo "" >> $LOGFILE

echo

echo "All done $USER. You can now look at your browser and log in with the appropriate information as defined in 'lib/tasks/populate.rake'"
sleep 5

echo

echo "The current window will soon close in order for you to neatly move your workspace to the newly opened terminal window."
sleep 4

echo

echo "Allow Spork ~2 minutes to run all ~250+ tests."
sleep 3

echo

echo "✔ Completed on $(date +%m-%d-%Y) at $(date +%T)"
sleep 5

echo

echo "Ceau!"
sleep 1

exit
