development:
  adapter: postgresql
  encoding: utf8
  database: amp3rsand
  pool: 5
  username: naathyn
  password: 12081
  timeout: 5000

test: &test
  adapter: postgresql
  encoding: utf8
  database: amp3test
  pool: 5
  username: naathyn
  password: 12081
  timeout: 5000
