development:
  adapter: mysql
  encoding: utf8
  database: amp_dev
  pool: 5
  username: root
  password: 12081
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ampersand
  pool: 5
  timeout: 5000
