development:
  adapter: mysql
  encoding: utf8
  database: amp_dev
  pool: 5
  username: 
  password: 
  timeout: 5000

test: &test
  adapter: mysql
  encoding: utf8
  database: amp_test
  pool: 5
  username: 
  password: 
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ampersand
  pool: 5
  timeout: 5000
